name: Build Desktop Application

on:
  push:
    tags:
      - "*"

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
      # Helpful reference https://github.com/samuelmeuli/mini-diary/blob/master/.github/workflows/release.yml
      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.3.0
        # if: contains(github.ref, "v0.")
        with:
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
